# Change these first
owner: Hypereds # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Hypereds
    url: https://www.hypereds.com
    method: GET
    icon: https://www.hypereds.com/favicon.ico
  - name: gestion de riesgos
    url: https://www.gestionderiesgosmineros.com
    icon: https://www.gestionderiesgosmineros.com/favicon.ico
  - name: Imac
    url: https://www.interelectricasimacsas.com
  

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "🚦 **Hyperds Cloud Service Status**"
  introMessage: "🔄 This page shows the current status of our SaaS services. The information is updated automatically every 5 minutes. 🛠️ If there is any maintenance or incident, we will report it here in real time."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
